apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  namespace: tektontutorial
spec:
  replicas: 6
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: db
        image: registry.redhat.io/rhscl/mysql-80-rhel7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
