

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: node-pipeline
spec:
  params:
    - name: contextDir
      description: the context directory from where to build the application
    - name: destinationImage
      description: the fully qualified image name
    - name: storageDriver
      description: Use storage driver type vfs if you are running on OpenShift.
      type: string
      default: vfs
  workspaces:
    - name: source
  tasks:
    - name: clone-build-push
      taskRef:
        name: tektonmustafa
      workspaces:
        - name: source
          workspace: source
          
      params:
        - name: contextDir
          value: $(params.contextDir)
        - name: destinationImage
          value: $(params.destinationImage)
        - name: storageDriver
          value: $(params.storageDriver)
    - name: update-k8s-deployment
      taskRef:
        name: openshift-client
      runAfter:
        - clone-build-push
      workspaces:
        - name: source
          workspace: source
      params:
        - name: SCRIPT
          value: |
            #!/usr/bin/env bash

            tag=$(cat "$(workspaces.source.path)"/tag.txt)
            kubectl set image deployment/nodejs-deployment httpd=docker.io/mustafastakater/mustafa_repo:"$tag" -n tektontutorial



