---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: tektontt
  namespace: tektontutorial
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: staging
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: TaskRun
      metadata:
       generateName: tknmustafa
       labels:
         tekton.dev/task: git-clone
      spec:
       taskRef:
         name: tektonmustafa
       params:
         - name: url
           value: https://github.com/self-tuts/Nodejs-application-with-docker
       workspaces:
         - name: source
           persistentVolumeClaim:
             claimName: my-pvc