kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodejs-deployment
  namespace: tektontutorial
spec:
  replicas: 4
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: docker.io/mustafastakater/mustafa_repo:ae84180
          ports:
            - containerPort: 9005
              protocol: TCP
          imagePullPolicy: Always
---

kind: Service
apiVersion: v1
metadata:
  name: nodejs-svc
  namespace: tektontutorial
spec:
  type: ClusterIP
  selector:
    app: httpd
  ports:
    - name: nodejs-port
      protocol: TCP
      port: 9005
---

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: nodejs-route
  namespace: tektontutorial
spec:  
  to:
    kind: Service
    name: nodejs-svc
    weight: 100
  port:
    targetPort: 9005
